local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set('n', 'f', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, { remap = true, desc = "Hop to the next character after the cursor" })
vim.keymap.set('n', 'F', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, { remap = true, desc = "Hop to the next character before the cursor" })
vim.keymap.set('n', 't', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, { remap = true, desc = "Hop to the previous character after the cursor" })
vim.keymap.set('n', 'T', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { remap = true, desc = "Hop to the previous character before the cursor" })
vim.keymap.set('n', 'T', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { remap = true, desc = "Hop to the previous character before the cursor" })
vim.keymap.set('n', ';', function()
  hop.hint_char2({ current_line_only = false, hint_offset = 1 })
end, { remap = true, desc = "Hop to the previous character before the cursor" })
